### ISSUE TITLE
To-do demos that I want to do

### ISSUE THREAD

**Issue by benmiller314** [benmiller314/cdm-demo2#1]
- [x] Making markdown lists by using `- [ ]` (and noting both the space between the brackets and the list bullet
- [x] Marking individual tasks complete with `- [x]`
- [x] Automatic syncing of issues into project columns

**Comment by benmiller314** [comment]
- [x] responding to issues for non-threaded conversation

**Comment by benmiller314** [comment]
* [x] referring to [particular prior comments](https://github.com/benmiller314/cdm-demo2/issues/1#issue-271707783) to simulate threaded conversation
* [ ] finding the link by hovering over the timestamp of the previous comment in the issue

**Comment by benmiller314** [comment]
- [x] alerting particular group members by "atting" them, like this: @benmiller314 
- [ ] assigning someone to the task represented by the issue by using the "Assignees" box at the side
